// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtHYljaNjXTofPNFew7IIC1cfDbOcaQYQ',
    appId: '1:1046681190221:web:d814d92ab5b65874fd0104',
    messagingSenderId: '1046681190221',
    projectId: 'casaproy-3459f',
    authDomain: 'casaproy-3459f.firebaseapp.com',
    storageBucket: 'casaproy-3459f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyANnao0TFi418amB8gURI50DzT3Sh0Iq74',
    appId: '1:1046681190221:android:64469a67eb55755efd0104',
    messagingSenderId: '1046681190221',
    projectId: 'casaproy-3459f',
    storageBucket: 'casaproy-3459f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2a9plsKoDl5mXNY4V3-QooiObzN4BqvY',
    appId: '1:1046681190221:ios:b73a82349f4540a6fd0104',
    messagingSenderId: '1046681190221',
    projectId: 'casaproy-3459f',
    storageBucket: 'casaproy-3459f.firebasestorage.app',
    iosBundleId: 'com.alejandro.casaproy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2a9plsKoDl5mXNY4V3-QooiObzN4BqvY',
    appId: '1:1046681190221:ios:b73a82349f4540a6fd0104',
    messagingSenderId: '1046681190221',
    projectId: 'casaproy-3459f',
    storageBucket: 'casaproy-3459f.firebasestorage.app',
    iosBundleId: 'com.alejandro.casaproy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDtHYljaNjXTofPNFew7IIC1cfDbOcaQYQ',
    appId: '1:1046681190221:web:d1e2c6d6c4b08b0afd0104',
    messagingSenderId: '1046681190221',
    projectId: 'casaproy-3459f',
    authDomain: 'casaproy-3459f.firebaseapp.com',
    storageBucket: 'casaproy-3459f.firebasestorage.app',
  );
}
